jobs:
- job: Build
  timeoutInMinutes: 90
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: Docker@2
    displayName: 'Run privileged container'
    inputs:
      command: run
      arguments: '--rm --privileged multiarch/qemu-user-static:register --reset'
  - task: UniversalPackages@0
    displayName: 'Download cython'
    inputs:
      command: download
      vstsFeed: 'arm64'
      vstsFeedPackage: 'cython'
      vstsPackageVersion: 0.29.13
      downloadDirectory: '$(Build.SourcesDirectory)/stretch-slim/python3.5/grpcio/prereqs'      
  - task: Docker@2
    displayName: build grpcio for arm64v8
    inputs:
      containerRegistry: 'acr-serviceconnection'
      command: build
      Dockerfile: stretch-slim/python3.5/grpcio/Dockerfile
      arguments: '-t arm64v8/python3.5-grpcio --build-arg DOCKER_REGISTRY=$(DOCKER_REGISTRY)'
      addPipelineData: false

  - task: Bash@3
    displayName: 'copy wheel'
    inputs:
      targetType: 'inline'
      script: |
        docker create -ti --name grpcio arm64v8/python3.5-grpcio bash
        docker cp grpcio:/dist $(Build.ArtifactStagingDirectory)/dist
        docker rm -fv grpcio

  - task: UniversalPackages@0
    displayName: 'upload wheel'
    inputs:
      command: 'publish'
      publishDirectory: '$(Build.ArtifactStagingDirectory)/dist'
      feedsToUsePublish: 'internal'
      vstsFeedPublish: 'arm64'
      versionOption: 'custom'
      versionPublish: '1.23.0'
      vstsFeedPackagePublish: 'grpcio'
      packagePublishDescription: 'grpcio built with arm64v8/python3.5'