jobs:
- job: Build
  pool:
    name: 'Self-hosted Ubuntu 16.04'
  steps:
  - task: Docker@2
    displayName: 'Run priviledged container'
    inputs:
      command: run
      arguments: '--rm --privileged multiarch/qemu-user-static:register --reset'
     
  - task: Docker@2
    displayName: build
    inputs:
      containerRegistry: 'acr-serviceconnection'
      command: build
      Dockerfile: ubuntu16.04/python3.5/h5py/Dockerfile
      arguments: '-t arm64v8/python3.5-h5py --build-arg DOCKER_REGISTRY=$(DOCKER_REGISTRY)'
      addPipelineData: false

  - task: Bash@3
    displayName: 'Copy wheel'
    inputs:
      targetType: 'inline'
      script: |
        docker create -ti --name h5py arm64v8/python3.5-h5py bash
        docker cp h5py:/dist $(Build.ArtifactStagingDirectory)/dist
        docker rm -fv h5py

  - task: UniversalPackages@0
    displayName: 'Publish package'
    inputs:
      command: 'publish'
      publishDirectory: '$(Build.ArtifactStagingDirectory)/dist'
      feedsToUsePublish: 'internal'
      vstsFeedPublish: 'arm64'
      versionOption: 'custom'
      versionPublish: '2.10.0'
      vstsFeedPackagePublish: 'h5py'
      packagePublishDescription: 'h5py built with arm64v8/python3.5'