jobs:
- job: Build
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: Docker@2
    displayName: 'Run priviledged container'
    inputs:
      command: run
      arguments: '--rm --privileged multiarch/qemu-user-static:register --reset'

  - task: Docker@2
    displayName: 'build numpy for arm64v8'
    inputs:
      containerRegistry: 'acr-serviceconnection'
      command: build
      Dockerfile: ubuntu16.04/python3.5/numpy/Dockerfile
      arguments: '-t arm64v8/python3.5-numpy --build-arg DOCKER_REGISTRY=$(DOCKER_REGISTRY)'
      addPipelineData: false

  - task: Bash@3
    displayName: 'copy wheel'
    inputs:
      targetType: 'inline'
      script: |
        docker create -ti --name numpy arm64v8/python3.5-numpy bash
        docker cp numpy:/dist $(Build.ArtifactStagingDirectory)/dist
        docker rm -fv numpy

  - task: UniversalPackages@0
    displayName: 'upload wheel'
    inputs:
      command: 'publish'
      publishDirectory: '$(Build.ArtifactStagingDirectory)/dist'
      feedsToUsePublish: 'internal'
      vstsFeedPublish: 'arm64v8'
      versionOption: 'custom'
      versionPublish: '1.16.4'
      vstsFeedPackagePublish: 'numpy'
      packagePublishDescription: 'numpy built with arm64v8/python3.5'