jobs:
- job: Build
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: Docker@2
    displayName: 'Run priviledged container'
    inputs:
      command: run
      arguments: '--rm --privileged multiarch/qemu-user-static:register --reset'
  - task: UniversalPackages@0
    displayName: 'Download numpy'
    inputs:
      command: download
      vstsFeed: 'arm64v8'
      vstsFeedPackage: 'numpy'
      vstsPackageVersion: 1.16.4
      downloadDirectory: '$(Build.SourcesDirectory)/ubuntu16.04/python3.5/h5py/prereqs'   
  - task: Docker@2
    displayName: build h5py for arm64v8
    inputs:
      containerRegistry: 'acr-serviceconnection'
      command: build
      Dockerfile: ubuntu16.04/python3.5/h5py/Dockerfile
      arguments: '-t arm64v8/python3.5-h5py --build-arg DOCKER_REGISTRY=$(DOCKER_REGISTRY)'
      addPipelineData: false

  - task: Bash@3
    displayName: 'copy wheel'
    inputs:
      targetType: 'inline'
      script: |
        docker create -ti --name h5py arm64v8/python3.5-h5py bash
        docker cp h5py:/dist $(Build.ArtifactStagingDirectory)/dist
        docker rm -fv h5py

  - task: UniversalPackages@0
    displayName: 'upload wheel'
    inputs:
      command: 'publish'
      publishDirectory: '$(Build.ArtifactStagingDirectory)/dist'
      feedsToUsePublish: 'internal'
      vstsFeedPublish: 'arm64v8'
      versionOption: 'custom'
      versionPublish: '2.10.0'
      vstsFeedPackagePublish: 'h5py'
      packagePublishDescription: 'h5py built with arm64v8/python3.5'